---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 13.2.20
  roles_path: roles/
platforms:
#  - name: ubuntu-16.04
   - name: centos-7.3

suites:
  - name: abcd

    provisioner:
      roles_path: roles

    run_list:
#        - recipe[timezone::default]
#      - recipe[limits::default]
#      - recipe[chrony::default]
#      - recipe[filebeat::default]
#      - recipe[basic_packages::default]
#      - recipe[nginx::default]
#       - recipe[php::default]
#       - recipe[node::default]
#       - recipe[selinux_conf::default]
#       - role[common]
#       - recipe[zabbix::default]
#      - recipe[awscli::default]
#       - recipe[mongodb::default]a
#       - recipe[basic_packages::default]
#        - recipe[host_name::default]
#         - recipe[users::default]
#      -  recipe[redis::default]
#      - recipe[php::default]
       - role[busdekho]
#      - recipe[httpd::busdekho-conf]
#      - recipe[rabbitmq::default]
    attributes:
