# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'nvm', '~> 0.1.7'
cookbook 'selinux', '~> 2.1.0'
cookbook 'ec2-tags-ohai-plugin', '~> 0.2.4'

cookbook 'selinux_conf', path: 'cookbooks/selinux_conf'
cookbook 'node', path: 'cookbooks/node'
cookbook 'nginx', path: 'cookbooks/nginx'
cookbook 'timezone', path: 'cookbooks/timezone'
cookbook 'basic_packages', path: 'cookbooks/basic_packages'
cookbook 'limits', path: 'cookbooks/limits'
cookbook 'filebeat', path: 'cookbooks/filebeat'
cookbook 'zabbix', path: 'cookbooks/zabbix'
cookbook 'awscli', path: 'cookbooks/awscli'
cookbook 'mongodb', path:'cookbooks/mongodb'
cookbook 'hostname', '~> 0.4.2'
cookbook 'host_name', path:'cookbooks/host_name'
cookbook 'hostsfile', '~> 3.0.1'
cookbook 'users', path: 'cookbooks/users'
cookbook 'php', path: 'cookbooks/php'
cookbook 'swap', '~> 2.1.0'
cookbook 'chrony', path: 'cookbooks/chrony'
cookbook 'encrypt', path: 'cookbooks/encrypt'
cookbook 'redis', path: 'cookbooks/redis'
cookbook 'httpd', path: 'cookbooks/httpd'
cookbook 'rabbitmq', path: 'cookbooks/rabbitmq'
cookbook 'java', path: 'cookbooks/java'
